substitutions:
  name: "display-3digit-7seg"
  friendly_name: "Test 3 Digit 7 Seg display"

esphome:
  name: "display-3digit-7seg"
  friendly_name: "Test 3 Digit 7 Seg display"

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
    version: "5.3.1"
    platform_version: 6.9.0

logger:
  level: INFO
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true

web_server:
  port: 80
  version: 3
  sorting_groups:
  - id: sorting_group_digit
    name: "Digit 1-3"
    sorting_weight: 10
  - id: sorting_group_segments
    name: "Segment A-G"
    sorting_weight: 40
  - id: sorting_group_dot
    name: "Dot DP"
    sorting_weight: 60
  - id: sorting_group_service
    name: "Service"
    sorting_weight: 90

button:
  - platform: restart
    name: "Restart"
    web_server:
      sorting_group_id: sorting_group_service

switch:
  # https://esphome.io/components/switch/gpio.html#gpio-switch

  # Digits
  - platform: gpio
    name: "Pin 8, Digit 3 (GPIO11)"
    id: pin_GPIO11
    pin:
      number: GPIO11
      mode: 
        output: true
    restore_mode: ALWAYS_OFF
    web_server:
      sorting_group_id: sorting_group_digit
      sorting_weight: 1
    on_turn_on:
    - logger.log: "Switch (GPIO11) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO11) Turned Off!"

  - platform: gpio
    name: "Pin 9, Digit 2 (GPIO18)"
    id: pin_GPIO18
    pin:
      number: GPIO18
      mode: 
        output: true
    restore_mode: ALWAYS_OFF
    web_server:
      sorting_group_id: sorting_group_digit
      sorting_weight: 2
    on_turn_on:
    - logger.log: "Switch (GPIO18) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO18) Turned Off!"

  - platform: gpio
    name: "Pin 12, Digit 1 (GPIO21)"
    id: pin_GPIO21
    pin:
      number: GPIO21
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_digit
      sorting_weight: 3
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO21) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO21) Turned Off!"

  # DOT
  - platform: gpio
    name: "Pin 3, DP - dot (GPIO22)"
    id: pin_GPIO22
    pin:
      number: GPIO22
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_dot
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO22) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO22) Turned Off!"

  # Segments
  - platform: gpio
    name: " Pin 11 (A) - (GPIO20)"
    id: pin_GPIO20
    pin:
      number: GPIO20
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_segments
      sorting_weight: 1
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO20) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO20) Turned Off!"

  - platform: gpio
    name: " Pin 7 (B) - (GPIO10)"
    id: pin_GPIO10
    pin:
      number: GPIO10
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_segments
      sorting_weight: 2
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO10) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO10) Turned Off!"

  - platform: gpio
    name: " Pin 4 (C) - (GPIO2)"
    id: pin_GPIO2
    pin:
      number: GPIO2
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_segments
      sorting_weight: 3
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO2) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO2) Turned Off!"

  - platform: gpio
    name: " Pin 2 (D) - (GPIO1)"
    id: pin_GPIO1
    pin:
      number: GPIO1
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_segments
      sorting_weight: 4
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO1) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO1) Turned Off!"

  - platform: gpio
    name: " Pin 1 (E) - (GPIO0)"
    id: pin_GPIO0
    pin:
      number: GPIO0
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_segments
      sorting_weight: 5
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO0) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO0) Turned Off!"

  - platform: gpio
    name: " Pin 10 (F) - (GPIO19)"
    id: pin_GPIO19
    pin:
      number: GPIO19
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_segments
      sorting_weight: 6
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO19) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO19) Turned Off!"

  - platform: gpio
    name: " Pin 5 (G) - (GPIO3)"
    id: pin_GPIO3
    pin:
      number: GPIO3
      mode: 
        output: true
    web_server:
      sorting_group_id: sorting_group_segments
      sorting_weight: 7
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - logger.log: "Switch (GPIO3) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO3) Turned Off!"
  
# END